- name: Install Nagios plugins package
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nagios-plugins
  tags:
    - monitoring

- name: Create monitoring folder structure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ monitoring_path }}"
    - "{{ monitoring_bin_path }}"
    - "{{ monitoring_log_path }}"
  tags:
    - monitoring

- name: Create check scripts
  template:
    src: check.sh.j2
    dest: "{{ monitoring_bin_path }}/check_{{ item.name }}.sh"
    owner: root
    group: root
    mode: 0755
  vars:
    check_name: "{{ item.name }}"
    check_cmd: "{{ item.cmd }}"
  with_items: "{{ monitoring_checks }}"
  tags:
    - monitoring

- name: Create master script to run check scripts
  template:
    src: monitoring.sh.j2
    dest: "{{ monitoring_bin_path }}/monitoring.sh"
    owner: root
    group: root
    mode: 0755
  tags:
    - monitoring

- name: Add cronjob to run master script
  cron:
    name: "Perform Monitoring Checks"
    minute: "*/5"
    job: "{{ monitoring_bin_path }}/monitoring.sh"
    user: root
  tags:
    - monitoring
